CREATE TABLE IF NOT EXISTS Notes(
    Id INT PRIMARY KEY AUTOINCREMENT,
    Tittel TEXT NOT NULL,
    Body TEXT NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO Notes (Tittel, Body)
VALUES ('First note','This is the very first note');

CREATE TABLE IF NOT EXISTS Todos(
    Id INT PRIMARY KEY AUTOINCREMENT,
    Text TEXT NOT NULL,
    Done INTEGER DEFAULT 0
)