-- Notes table (for your notes app)
CREATE TABLE IF NOT EXISTS Notes (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Tittel TEXT,
  Body TEXT,
  CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Todos table (for your todo list)
CREATE TABLE IF NOT EXISTS Todos (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Text TEXT,
  Done INTEGER DEFAULT 0
);